"""rename task name to twitter_name

Revision ID: e9bbdec80ff0
Revises: 9d9c561d3f78
Create Date: 2025-09-12 15:49:38.991209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bbdec80ff0'
down_revision: Union[str, Sequence[str], None] = '9d9c561d3f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加新列（允许为空）
    op.add_column('tasks', sa.Column('twitter_name', sa.String(length=100), nullable=True))
    
    # 2. 将旧列的数据复制到新列
    op.execute("UPDATE tasks SET twitter_name = name")
    
    # 3. 将新列设为非空
    op.alter_column('tasks', 'twitter_name', nullable=False)
    
    # 4. 删除旧列
    op.drop_column('tasks', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加旧列（允许为空）
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    # 2. 将新列的数据复制到旧列
    op.execute("UPDATE tasks SET name = twitter_name")
    
    # 3. 将旧列设为非空
    op.alter_column('tasks', 'name', nullable=False)
    
    # 4. 删除新列
    op.drop_column('tasks', 'twitter_name')
    # ### end Alembic commands ###
