"""Add user_wallet column to tasks table

Revision ID: f189e6c55f71
Revises: e9bbdec80ff0
Create Date: 2025-09-13 21:26:42.366021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f189e6c55f71'
down_revision: Union[str, Sequence[str], None] = 'e9bbdec80ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_wallet', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'user_wallet')
    # ### end Alembic commands ###
